pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'prajyotrane111/flask-app'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir('Project_P1') {
                    bat '"C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python313\\python.exe" -m pip install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Project_P1') {
                    bat 'pytest'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Project_P1') {
                    bat 'docker build -t %DOCKER_IMAGE%:%IMAGE_TAG% .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-cred',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    bat '''
                        echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                        docker push %DOCKER_IMAGE%:%IMAGE_TAG%
                        docker logout
                    '''
                }
            }
        }
    }
}
