pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'prajyotrane111/flask-app'
        IMAGE_TAG = "${BUILD_NUMBER}"
        DATABASE_URL = 'mysql+pymysql://root:root@mysql-ci:3306/ProjectP1'
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir('Project_P1') {
                    sh 'python3 -m venv .venv'
                    sh '.venv/bin/python -m pip install --upgrade pip'
                    sh '.venv/bin/python -m pip install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Project_P1') {
                    sh '''
                        export DATABASE_URL="$DATABASE_URL"
                        .venv/bin/python -m pytest
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Project_P1') {
                    sh 'docker build -t $DOCKER_IMAGE:$IMAGE_TAG .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'prajotDocker',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login \
                            -u "$DOCKER_USER" \
                            --password-stdin

                        docker push "$DOCKER_IMAGE:$IMAGE_TAG"

                        docker logout
                    '''
                }
            }
        }
    }
}
