"""Add SLA due dates to tickets

Revision ID: 10cba1a3d053
Revises: a58f4c77f7ee
Create Date: 2026-08-23 11:29:09.695959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cba1a3d053'
down_revision = 'a58f4c77f7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolution_due_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('resolution_due_at')
        batch_op.drop_column('response_due_at')

    with op.batch_alter_table('ticket_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
