"""Create ticket assignments table

Revision ID: e34f97555f44
Revises: eb1fe1480439
Create Date: 2026-08-20 13:05:35.900448

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e34f97555f44'
down_revision = 'eb1fe1480439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ticket_assignments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('agent_id', sa.Integer(), nullable=False),
        sa.Column(
            'assigned_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('assigned_by', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['agent_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['assigned_by'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['ticket_id'],
            ['tickets.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_assignments')
    # ### end Alembic commands ###
