"""Create SLA rules table

Revision ID: f26bd19d271a
Revises: d2111b273cee
Create Date: 2026-08-20 14:06:40.832247

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f26bd19d271a'
down_revision = 'd2111b273cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sla_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('priority', sa.String(length=20), nullable=False),
        sa.Column('response_time_hours', sa.Integer(), nullable=False),
        sa.Column('resolution_time_hours', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('priority'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sla_rules')
    # ### end Alembic commands ###
