apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: servicedesk
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  DATABASE_URL: mysql+pymysql://root:root@mysql-service:3306/ProjectP1